services:
  - type: web
    name: ensmg-mofi
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --no-input && python manage.py flush --no-input && python manage.py create_admin && python manage.py collectstatic --no-input
    startCommand: gunicorn ensmg_mofi.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ensmg-mofi-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: BOOTSTRAP_KEY
        value: "ensmg2025"
      - key: PYTHON_VERSION
        value: "3.11.0"

databases:
  - name: ensmg-mofi-db
    databaseName: ensmg_mofi
    user: ensmg_admin
    plan: free
