# Generated by Django 6.0.3 on 2026-04-01 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la certification')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duree', models.CharField(blank=True, max_length=100, verbose_name='Durée')),
                ('tarif_etudiant', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tarif étudiant (FCFA)')),
                ('tarif_professionnel', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tarif professionnel (FCFA)')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inscrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('activite', models.CharField(choices=[('etudiant', 'Étudiant'), ('professionnel', 'Professionnel')], default='etudiant', max_length=20, verbose_name='Activité')),
                ('source', models.CharField(choices=[('manuel', 'Manuel'), ('excel', 'Import Excel')], default='manuel', max_length=20, verbose_name='Source')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Inscrit',
                'verbose_name_plural': 'Inscrits',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la cohorte')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohortes', to='inscriptions.certification', verbose_name='Certification')),
            ],
            options={
                'verbose_name': 'Cohorte',
                'verbose_name_plural': 'Cohortes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('en_formation', 'En formation'), ('abandon', 'Abandon'), ('formation_terminee', 'Formation terminée'), ('certifie', 'Certifié')], default='inscrit', max_length=20, verbose_name='Statut')),
                ('montant_du', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant dû (FCFA)')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('cohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inscriptions.cohorte', verbose_name='Cohorte')),
                ('inscrit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inscriptions.inscrit', verbose_name='Inscrit')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('inscrit', 'cohorte')},
            },
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'attestation")),
                ('date_delivrance', models.DateField(default=django.utils.timezone.now, verbose_name='Date de délivrance')),
                ('contenu_pdf', models.BinaryField(blank=True, help_text='PDF stocké en base de données (persist sur tous les hébergeurs).', null=True, verbose_name='Contenu PDF')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='inscriptions.inscription', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': 'Attestation',
                'verbose_name_plural': 'Attestations',
                'ordering': ['-date_delivrance', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now, verbose_name='Date de paiement')),
                ('moyen_paiement', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('stripe', 'Stripe'), ('especes', 'Espèces'), ('virement', 'Virement bancaire')], default='especes', max_length=20, verbose_name='Moyen de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='inscriptions.inscription', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement', '-created_at'],
            },
        ),
    ]
