# Generated by Django 4.2.16 on 2026-04-26 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom de la certification")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("duree", models.CharField(blank=True, max_length=100, verbose_name="Durée")),
                (
                    "a_options",
                    models.BooleanField(
                        default=False,
                        help_text="Si activé, la certification est organisée en options (ex: A1, A2…). Chaque option dispose de ses propres cohortes et tarifs.",
                        verbose_name="Avec options",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cohorte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom de la cohorte")),
                (
                    "date_debut",
                    models.DateField(blank=True, null=True, verbose_name="Date de début"),
                ),
                ("date_fin", models.DateField(blank=True, null=True, verbose_name="Date de fin")),
                ("actif", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohortes",
                        to="inscriptions.certification",
                        verbose_name="Certification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cohorte",
                "verbose_name_plural": "Cohortes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="CompteApprenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mdp_change",
                    models.BooleanField(default=False, verbose_name="Mot de passe changé"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Compte Apprenant",
                "verbose_name_plural": "Comptes Apprenants",
            },
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("pre_inscrit", "Pré-inscrit"),
                            ("inscrit", "Inscrit"),
                            ("en_formation", "En formation"),
                            ("abandon", "Abandon"),
                            ("formation_terminee", "Formation terminée"),
                            ("certifie", "Certifié"),
                        ],
                        db_index=True,
                        default="inscrit",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "montant_du",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Montant dû (FCFA)"
                    ),
                ),
                (
                    "date_inscription",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "cohorte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="inscriptions.cohorte",
                        verbose_name="Cohorte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
                "ordering": ["-date_inscription"],
            },
        ),
        migrations.CreateModel(
            name="Inscrit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(db_index=True, max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(db_index=True, max_length=100, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(blank=True, max_length=30, verbose_name="Téléphone"),
                ),
                (
                    "activite",
                    models.CharField(
                        choices=[("etudiant", "Étudiant"), ("professionnel", "Professionnel")],
                        default="etudiant",
                        max_length=20,
                        verbose_name="Activité",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manuel", "Manuel"),
                            ("excel", "Import Excel"),
                            ("portail", "Portail en ligne"),
                        ],
                        default="manuel",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                ("adresse", models.CharField(blank=True, max_length=255, verbose_name="Adresse")),
                (
                    "universite",
                    models.CharField(blank=True, max_length=200, verbose_name="Université"),
                ),
                (
                    "entreprise",
                    models.CharField(blank=True, max_length=200, verbose_name="Entreprise"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "date_inscription",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription"),
                ),
            ],
            options={
                "verbose_name": "Inscrit",
                "verbose_name_plural": "Inscrits",
                "ordering": ["-date_inscription"],
            },
        ),
        migrations.CreateModel(
            name="OptionCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom de l'option")),
                ("actif", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="inscriptions.certification",
                        verbose_name="Certification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option de certification",
                "verbose_name_plural": "Options de certification",
                "ordering": ["nom"],
                "unique_together": {("certification", "nom")},
            },
        ),
        migrations.CreateModel(
            name="TypeTarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom du tarif")),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Montant (FCFA)"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types_tarif",
                        to="inscriptions.certification",
                        verbose_name="Certification",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types_tarif",
                        to="inscriptions.optioncertification",
                        verbose_name="Option",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de tarif",
                "verbose_name_plural": "Types de tarif",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant (FCFA)"
                    ),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "moyen_paiement",
                    models.CharField(
                        choices=[
                            ("wave", "Wave"),
                            ("orange_money", "Orange Money"),
                            ("intouch", "InTouch Sénégal"),
                            ("carte", "Carte bancaire"),
                            ("especes", "Espèces"),
                            ("virement", "Virement bancaire"),
                        ],
                        db_index=True,
                        default="especes",
                        max_length=20,
                        verbose_name="Moyen de paiement",
                    ),
                ),
                (
                    "reference",
                    models.CharField(blank=True, max_length=100, verbose_name="Référence"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("confirme", "Confirmé"), ("en_attente", "En attente")],
                        default="confirme",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("recu_pdf", models.BinaryField(blank=True, null=True, verbose_name="Reçu PDF")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="inscriptions.inscription",
                        verbose_name="Inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-date_paiement", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type_notif",
                    models.CharField(
                        choices=[
                            ("nouvelle_certification", "Nouvelle certification disponible"),
                            ("attestation_generee", "Attestation générée"),
                            ("paiement_confirme", "Paiement confirmé"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                ("lu", models.BooleanField(default=False, verbose_name="Lu")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("lien", models.CharField(blank=True, max_length=200, verbose_name="Lien")),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="inscriptions.compteapprenant",
                        verbose_name="Destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.AddField(
            model_name="inscription",
            name="inscrit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscriptions",
                to="inscriptions.inscrit",
                verbose_name="Inscrit",
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="type_tarif",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inscriptions",
                to="inscriptions.typetarif",
                verbose_name="Type de tarif",
            ),
        ),
        migrations.AddField(
            model_name="compteapprenant",
            name="inscrit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compte_apprenant",
                to="inscriptions.inscrit",
                verbose_name="Inscrit",
            ),
        ),
        migrations.AddField(
            model_name="compteapprenant",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compte_apprenant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="cohorte",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cohortes",
                to="inscriptions.optioncertification",
                verbose_name="Option",
            ),
        ),
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro d'attestation"
                    ),
                ),
                (
                    "date_delivrance",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date de délivrance"
                    ),
                ),
                (
                    "contenu_pdf",
                    models.BinaryField(
                        blank=True,
                        help_text="PDF stocké en base de données (persist sur tous les hébergeurs).",
                        null=True,
                        verbose_name="Contenu PDF",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="inscriptions.inscription",
                        verbose_name="Inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attestation",
                "verbose_name_plural": "Attestations",
                "ordering": ["-date_delivrance", "-generated_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="inscription",
            unique_together={("inscrit", "cohorte")},
        ),
    ]
