# Generated by Django 6.0.3 on 2026-03-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('activite', models.CharField(max_length=200, verbose_name='Formation / Activité')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('source', models.CharField(choices=[('manuel', 'Saisie manuelle'), ('excel', 'Import Excel')], default='manuel', max_length=10, verbose_name='Source')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Inscrit',
                'verbose_name_plural': 'Inscrits',
                'ordering': ['-date_inscription', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('moyen_paiement', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('stripe', 'Stripe'), ('especes', 'Espèces'), ('virement', 'Virement bancaire')], max_length=20, verbose_name='Moyen de paiement')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Référence / N° de transaction')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('inscrit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='inscriptions.inscrit', verbose_name='Inscrit')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement', '-created_at'],
            },
        ),
    ]
