# Generated by Django 4.2.16 on 2026-04-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NomTypeTarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True, verbose_name="Nom")),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Nom de type de tarif",
                "verbose_name_plural": "Noms de types de tarif",
                "ordering": ["nom"],
            },
        ),
    ]
