# Generated by Django 4.2.29 on 2026-04-02 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_indexes_drf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('pre_inscrit', 'Pré-inscrit'), ('inscrit', 'Inscrit'), ('en_formation', 'En formation'), ('abandon', 'Abandon'), ('formation_terminee', 'Formation terminée'), ('certifie', 'Certifié')], db_index=True, default='inscrit', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='moyen_paiement',
            field=models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('paytech', 'PayTech'), ('carte', 'Carte bancaire'), ('stripe', 'Stripe'), ('especes', 'Espèces'), ('virement', 'Virement bancaire')], db_index=True, default='especes', max_length=20, verbose_name='Moyen de paiement'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('nouvelle_certification', 'Nouvelle certification disponible'), ('attestation_generee', 'Attestation générée'), ('paiement_confirme', 'Paiement confirmé')], max_length=30, verbose_name='Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lien', models.CharField(blank=True, max_length=200, verbose_name='Lien')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inscriptions.compteapprenant', verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
