# Generated by Django 6.0.3 on 2026-04-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0005_intouch'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='partenaire_logo',
            field=models.ImageField(blank=True, null=True, upload_to='partenaires/', verbose_name='Logo du partenaire'),
        ),
        migrations.AddField(
            model_name='certification',
            name='partenaire_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du partenaire'),
        ),
        migrations.AddField(
            model_name='certification',
            name='partenaire_titre_signataire',
            field=models.CharField(blank=True, default='Le Représentant', max_length=200, verbose_name='Titre du signataire partenaire'),
        ),
    ]
